### ISSUE TITLE
Integration testing issues

### ISSUE THREAD

**Issue by Robdel12** [wesm87/ember-datepicker#31]
I'm having issues with integration testing with this. No matter what I fill the field in with the test fails because it's returning todays date and time. 

`fillIn(".date", timeline.event_date);`

Here's what timeline looks like: 

``` javascript
var timeline = {
    id: 101,
    title: 'My new About',
    event_date: new Date(2014, 02, 03).toString(), //March 3rd, 2014
    description: "My new abouts description",
    is_published: "true"
  };
```

I've tried to to string it, adding just `2014-03-03` to the field, and keeping it as a date object without any luck.

**Comment by spovich** [comment]
I'm seeing this also.  Both `fillIn()` and manually setting the value of the input in a jQuery selector will show the value changed (when checked with jQuery), but the changed value won't register on the bound `date` attribute in the calling component `{{date-picker date=foo}}`.

Anyone have suggestions on this?

**Comment by Robdel12** [comment]
I ended up going with [another pikaday addon](https://github.com/edgycircle/ember-pikaday#test-helpers) that has test helpers.
